### ISSUE TITLE
[Question] What happened to depth images?

### ISSUE THREAD

**Issue by colejd** [bigboss-ps3dev/PS4EYECam#3]
Hello!

I noticed that your repo used to have some code for getting depth from the camera. It seems to be removed. From looking through the history, it looks like (and I'm making a big assumption here) you realized at some point that what you thought was the depth frame was actually regular data from the right camera, and then changed it? If that's not the case, would it be possible to get that depth information back?

Thank you!

**Comment by bigboss-ps3dev** [comment]
Hello, after some research playstation camera has not depth image at all. Sony is making all by software on ps4 side.

Each frame has per line:
header,audio,video left,video right, video interleave.

Video interleave is different resolution of video frames.

Old article that i published with information about it:

http://bigboss-eyetoy.blogspot.com/2015/02/reversing-playstation-4-camera.html

**Comment by colejd** [comment]
Ok, good to know. Thank you for the quick response!
